alias vi='hx'
alias vim='hx'
alias nano='hx'
alias less='bat --paging=always'
alias more='bat --paging=always'
alias screen='tmux'
alias terraform='tofu'
alias ls='ls --color=auto'
alias ll='ls -lat --color=auto'
alias top='htop'
alias grep='grep --color=auto'
alias ..='cd ..'
